# NOTE: This file only exists for IDE code completion.

[project]
name = "thermo-hygro-collector"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Koki Fukuda", email = "ko.fu.dev@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "micropython-rp2-rpi-pico2-w-stubs>=1.27.0.post1",
    "prometheus-remote-write-payload",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mpremote>=1.27.0",
]

[tool.uv]
package = false

[tool.uv.sources]
prometheus-remote-write-payload = { git = "https://github.com/ttk1/prometheus_remote_write_payload.git" }
